language: ruby
rvm:
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
    - spectest
env:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=3.7.3
notifications:
  email: false
gemfile: .gemfile
